apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: multiplayer-server
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/rejdeboer/multiplayer-server-deployment
  secretRef:
    name: multiplayer-deployment-github
