apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multiplayer-server
  namespace: default
spec:
  interval: 15m
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: multiplayer-server
