apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      restartPolicy: Never
      containers:
      - name: migration
        image: rejdeboer.azurecr.io/multiplayer-server:ff41531f56e056c56fd826c57ef8f362a65bf7fc
        command:
          - /bin/sh
          - -c
          - |
            echo "Starting migration"
            apk --no-cache add postgresql-client
            CGO_ENABLED=0 GOOS=linux go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
            export DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=verify-full&sslrootcert=/mnt/certificates/az-root.pem"
            migrate -database "${DATABASE_URL}" -path=db/migrations up
            echo "Migration finished"
        volumeMounts:
          - name: az-root-certificate
            mountPath: "/mnt/certificates"
            readOnly: true
        env:
          - name: DB_HOST
            value: multiplayer-server.postgres.database.azure.com
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: multiplayer-server
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: multiplayer-server-secrets
                key: postgres-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: multiplayer-server-secrets
                key: postgres-password
      volumes:
        - name: az-root-certificate
          configMap:
            name: az-root-certificate
