apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: default
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      restartPolicy: Never
      containers:
      - name: migration
        image: rejdeboer.azurecr.io/multiplayer-db-migration:4fa33a6581c1383da35d95cb9d1bdabd245721d1
        env:
          - name: ENVIRONMENT
            value: production
          - name: DB_HOST
            value: multiplayer-server.postgres.database.azure.com
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: multiplayer-server
          - name: DB_USERNAME
            value: multiplayer-server-aks
