apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pre-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./pre-deploy
  prune: true
  wait: true
  timeout: 5m0s
