apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multiplayer-server
  namespace: default
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /sync
            pathType: Prefix
            backend:
              service:
                name: multiplayer-websocket
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: multiplayer-server
                port:
                  number: 80
