apiVersion: v1
kind: Service
metadata:
  name: multiplayer-server-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000
  selector:
    app: multiplayer-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-server-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplayer-server
  template:
    metadata:
      labels:
        app: multiplayer-server
    spec:
      containers:
        - name: multiplayer-server
          image: rejdeboer.azurecr.io/multiplayer-server:064c9823be3ba094657eb2a41745a7ec7426655a
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          volumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
            - name: ENVIRONMENT
              value: production
            - name: PORT
              value: "8000"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "multiplayer-server"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: postgres-url
                  name: postgres-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: multiplayer-server-secrets
                  key: postgres-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: multiplayer-server-secrets
                  key: postgres-password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: multiplayer-server-secrets
                  key: jwt-secret-key
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "secret-provider"

