apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  interval: 24h
  url: https://helm.elastic.co
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  timeout: 5m
  interval: 10m
  chart:
    spec:
      chart: eck-elasticsearch
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: elasticsearch
        namespace: elasticsearch
      install:
        crds: Skip
      interval: 12h
