apiVersion: v1
kind: Namespace
metadata:
  name: kafka 
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 24h
  url: oci://quay.io/strimzi-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  timeout: 5m
  interval: 10m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.x"
      sourceRef:
        kind: HelmRepository
        name: kafka
        namespace: kafka
      interval: 12h
