apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider
spec:
  provider: azure
  parameters:
      usePodIdentity: "false"
      useVMManagedIdentity: "true"
      userAssignedIdentityID: "697223ca-2db0-4333-a699-a4ade0081a0e" 
      keyvaultName: "multiplayer-server-vault"
      objects:  |
        array:
          - |
            objectName: multiplayer-server-configuration
            objectType: secret # object types: secret, key, or cert
      tenantId: "33775a2a-f4ac-4722-9358-3764d5110404"
