kind: Pod
apiVersion: v1
metadata:
  name: busybox-secrets-store-inline-user-msi
spec:
  containers:
    - name: busybox
      image: registry.k8s.io/e2e-test-images/busybox:1.29-1
      command:
        - "/bin/sleep"
        - "10000"
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: multiplayer-server-configuration
              name: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: multiplayer-server-configuration
              name: postgres-password
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: multiplayer-server-configuration
              name: jwt-secret-key
