apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "697223ca-2db0-4333-a699-a4ade0081a0e" 
    keyvaultName: "multiplayer-server-vault"
    objects:  |
      array:
        - |
          objectName: postgres-username
          objectType: secret
        - |
          objectName: postgres-password
          objectType: secret
        - |
          objectName: jwt-secret-key
          objectType: secret
    tenantId: "33775a2a-f4ac-4722-9358-3764d5110404"
  secretObjects:
  - data:
    - key: postgres-username
      objectName: postgres-username
    - key: postgres-password
      objectName: postgres-password
    - key: jwt-secret-key
      objectName: jwt-secret-key
    secretName: multiplayer-server-configuration
    type: Opaque
