apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: default
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      # NOTE: Will be replaced by the Flux environment Kustomization
      vaultUrl: "https://xx-xxxx-xx.vault.azure.net"
      serviceAccountRef:
        name: workload-identity-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secret
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: azure-store

  target:
    name: cloudflare-secret
    creationPolicy: Owner

  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: cloudflare-api-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multiplayer-server-secrets
  namespace: default
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: azure-store

  target:
    name: multiplayer-server-secrets
    creationPolicy: Owner

  data:
  - secretKey: postgres-username
    remoteRef:
      key: postgres-username
  - secretKey: postgres-password
    remoteRef:
      key: postgres-password
  - secretKey: jwt-secret-key
    remoteRef:
      key: jwt-secret-key
