apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.20.2
      sourceRef:
        kind: HelmRepository
        name: cnpg-operator
        namespace: cnpg-system
      interval: 1m
