name: Deploy

on: [ push, pull_request ]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

permissions:
      id-token: write

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Deploy Terraform
        id: terraform
        uses: ./.github/actions/deploy-terraform
        with:
          BACKEND_STATE_KEY: "terraform.tfstate"
          BACKEND_BUCKET_NAME: "rejdeboertfstate"
          WORKING_DIRECTORY: ./terraform
        env:
          TF_VAR_github_org: ${{ github.repository_owner }}
          TF_VAR_github_repository: ${{ github.event.repository.name }}
          TF_VAR_github_token: ${{ secrets.GH_PAT }}

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets. ARM_SUBSCRIPTION_ID }}

      - name: Set resource group and cluster name
        id: set_aks_variables
        run: |
          echo "::set-output name=resource_group_name::$(terraform -chdir=terraform output -raw resource_group_name)"
          echo "::set-output name=cluster_name::$(terraform -chdir=terraform output -raw cluster_name)"

          # TODO: Github recommend using below method, but it doesn't seem to work
          # echo "{resource_group_name}={$(terraform -chdir=terraform output -raw resource_group_name)}" >> $GITHUB_STATE
          # echo "{cluster_name}={$(terraform -chdir=terraform output -raw cluster_name)}" >> $GITHUB_STATE

      - name: Set AKS context
        id: set_context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ steps.set_aks_variables.outputs.resource_group_name }}
          cluster-name: ${{ steps.set_aks_variables.outputs.cluster_name }}

  deploy:
    name: Deploy with Kubernetes and Flux
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: 'latest'

      - name: Apply deploy manifests for Flux
        run: |
          flux create secret git multiplayer-deployment-github --url https://github.com/${{ github.repository }} --username "${{ github.repository_owner }}" --bearer-token "${{ secrets.GH_PAT }}" --namespace default
          kubectl -n default apply -f gitrepository.yml
          kubectl -n default apply -f kustomization.yml
